apiVersion: v1

kind: Secret

metadata:
  name: website-secret
  namespace: dev

type: Opaque

stringData:
  DB_USERNAME: admin
  DB_PASSWORD: Password@123
  AWS_ACCESS_KEY: AKIA123456789
  AWS_SECRET_KEY: SECRET123456789