---
- hosts: web
  become: yes

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and Enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove default Apache files
      file:
        path: /var/www/html
        state: absent

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy Vishnu IT Solutions website files
      copy:
        src: ./projects/vishnu-it-solutions/app/
        dest: /var/www/html/
        mode: '0644'

    - name: Restart Apache
      service:
        name: apache2
        state: restarted