apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
      - ingress-nginx
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s