apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: website-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: website-alerts
    rules:

    - alert: WebsiteDown
      expr: probe_success == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Website is Down
        description: Vishnu IT Solutions website is not reachable.

    - alert: HighCPUUsage
      expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High CPU Usage
        description: CPU usage exceeded 80%.

    - alert: HighMemoryUsage
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High Memory Usage
        description: Memory usage exceeded 80%.